"""V0.4 added foreign key in Farm

Revision ID: c587b4a21ac9
Revises: dc4c3db8cc9c
Create Date: 2025-03-28 19:57:36.038002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c587b4a21ac9'
down_revision: Union[str, None] = 'dc4c3db8cc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
